### ISSUE TITLE
Similar project?

### ISSUE THREAD

**Issue by thehunmonkgroup** [simonmesmith/agentflow#44]
Saw your ycombinator post, thought I'd make you aware of a similar effort:

https://github.com/llm-workflow-engine/llm-workflow-engine has linear workflows (via Ansible integration), conversation threads, templating, provider/model presets, and OpenAI functions support.

I built it for the same reasons listed in the OP -- really seemed like a simple linear workflow manager would be incredibly useful.

**Comment by simonmesmith** [comment]
@thehunmonkgroup very cool! I wasn't aware of that project. It seems quite robust. I'm leaning towards something much lighter weight here, and this is very much a personal project right now. I'm going to close this issue but keep an eye out for great stuff from LWE.
